// Code generated by sqlc. DO NOT EDIT.
// source: internal/repository/queries/

package db

import (
	"context"
	"database/sql"
)

// DBTX is satisfied by both *sql.DB and *sql.Tx, allowing Queries to run
// inside or outside a transaction without changing call sites.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New creates a Queries bound to the given DBTX.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries holds a DBTX and exposes all generated query methods.
type Queries struct {
	db DBTX
}

// WithTx returns a new Queries bound to tx.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
