// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// User mirrors the users table.
type User struct {
	ID               uuid.UUID      `json:"id"`
	Email            sql.NullString `json:"email"`
	FullName         sql.NullString `json:"full_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	Phone            sql.NullString `json:"phone"`
	IsEmailVerified  bool           `json:"is_email_verified"`
	IsPhoneVerified  bool           `json:"is_phone_verified"`
	IsActive         bool           `json:"is_active"`
	ProfileCompleted bool           `json:"profile_completed"`
	HowHeard         sql.NullString `json:"how_heard"`
	HowHeardOther    sql.NullString `json:"how_heard_other"`
	TermsAcceptedAt  sql.NullTime   `json:"terms_accepted_at"`
	MarketingConsent bool           `json:"marketing_consent"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// AuthIdentity mirrors the auth_identities table.
type AuthIdentity struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	Provider           string         `json:"provider"`
	ProviderUid        string         `json:"provider_uid"`
	ProviderEmail      sql.NullString `json:"provider_email"`
	ProviderName       sql.NullString `json:"provider_name"`
	ProviderAvatar     sql.NullString `json:"provider_avatar"`
	AccessToken        sql.NullString `json:"access_token"`
	RefreshToken       sql.NullString `json:"refresh_token"`
	TokenExpiresAt     sql.NullTime   `json:"token_expires_at"`
	AppleNameCaptured  bool           `json:"apple_name_captured"`
	IsPrimary          bool           `json:"is_primary"`
	LastUsedAt         sql.NullTime   `json:"last_used_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// OtpSession mirrors the otp_sessions table.
type OtpSession struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	SessionToken string         `json:"session_token"`
	OtpHash      string         `json:"otp_hash"`
	Attempts     int32          `json:"attempts"`
	ExpiresAt    time.Time      `json:"expires_at"`
	UsedAt       sql.NullTime   `json:"used_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

// RefreshToken mirrors the refresh_tokens table.
// IpAddress is stored as TEXT (cast from INET by the queries).
type RefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	FamilyID  uuid.UUID      `json:"family_id"`
	DeviceID  sql.NullString `json:"device_id"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	CreatedAt time.Time      `json:"created_at"`
}

// UserForLogin extends User with the password_hash column.
// Used only during password-based login — never returned to clients.
type UserForLogin struct {
	ID               uuid.UUID      `json:"-"`
	Email            sql.NullString `json:"-"`
	FullName         sql.NullString `json:"-"`
	AvatarUrl        sql.NullString `json:"-"`
	Phone            sql.NullString `json:"-"`
	IsEmailVerified  bool           `json:"-"`
	IsPhoneVerified  bool           `json:"-"`
	IsActive         bool           `json:"-"`
	ProfileCompleted bool           `json:"-"`
	HowHeard         sql.NullString `json:"-"`
	HowHeardOther    sql.NullString `json:"-"`
	TermsAcceptedAt  sql.NullTime   `json:"-"`
	MarketingConsent bool           `json:"-"`
	LastLoginAt      sql.NullTime   `json:"-"`
	CreatedAt        time.Time      `json:"-"`
	UpdatedAt        time.Time      `json:"-"`
	PasswordHash     sql.NullString `json:"-"` // NULL for Google/Apple users
}

// ToUser converts UserForLogin to the standard User type for downstream use.
func (u UserForLogin) ToUser() User {
	return User{
		ID:               u.ID,
		Email:            u.Email,
		FullName:         u.FullName,
		AvatarUrl:        u.AvatarUrl,
		Phone:            u.Phone,
		IsEmailVerified:  u.IsEmailVerified,
		IsPhoneVerified:  u.IsPhoneVerified,
		IsActive:         u.IsActive,
		ProfileCompleted: u.ProfileCompleted,
		HowHeard:         u.HowHeard,
		HowHeardOther:    u.HowHeardOther,
		TermsAcceptedAt:  u.TermsAcceptedAt,
		MarketingConsent: u.MarketingConsent,
		LastLoginAt:      u.LastLoginAt,
		CreatedAt:        u.CreatedAt,
		UpdatedAt:        u.UpdatedAt,
	}
}

// BuyerProfileRow is the subset of buyer_profiles columns returned by auth queries.
// Array columns (saved_store_ids, preferred_category_ids) are intentionally
// excluded — auth only needs to confirm the profile exists.
type BuyerProfileRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	TotalOrders int32     `json:"total_orders"`
	TotalSpent  int64     `json:"total_spent"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
