// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// ── users ─────────────────────────────────────────────────────────────────────

const getUserByID = `
SELECT id, email, full_name, avatar_url, phone,
       is_email_verified, is_phone_verified, is_active,
       profile_completed, how_heard, how_heard_other,
       terms_accepted_at, marketing_consent, last_login_at,
       created_at, updated_at
FROM users WHERE id = $1`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var u User
	err := row.Scan(
		&u.ID, &u.Email, &u.FullName, &u.AvatarUrl, &u.Phone,
		&u.IsEmailVerified, &u.IsPhoneVerified, &u.IsActive,
		&u.ProfileCompleted, &u.HowHeard, &u.HowHeardOther,
		&u.TermsAcceptedAt, &u.MarketingConsent, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const getUserByEmail = `
SELECT id, email, full_name, avatar_url, phone,
       is_email_verified, is_phone_verified, is_active,
       profile_completed, how_heard, how_heard_other,
       terms_accepted_at, marketing_consent, last_login_at,
       created_at, updated_at
FROM users WHERE email = $1`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var u User
	err := row.Scan(
		&u.ID, &u.Email, &u.FullName, &u.AvatarUrl, &u.Phone,
		&u.IsEmailVerified, &u.IsPhoneVerified, &u.IsActive,
		&u.ProfileCompleted, &u.HowHeard, &u.HowHeardOther,
		&u.TermsAcceptedAt, &u.MarketingConsent, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

type UpsertUserByEmailParams struct {
	Email           string
	FullName        sql.NullString
	AvatarUrl       sql.NullString
	IsEmailVerified bool
}

const upsertUserByEmail = `
INSERT INTO users (email, full_name, avatar_url, is_email_verified)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) WHERE email IS NOT NULL
DO UPDATE SET
    last_login_at     = now(),
    updated_at        = now(),
    full_name         = COALESCE(users.full_name,  EXCLUDED.full_name),
    avatar_url        = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
    is_email_verified = users.is_email_verified OR EXCLUDED.is_email_verified
RETURNING id, email, full_name, avatar_url, phone,
          is_email_verified, is_phone_verified, is_active,
          profile_completed, how_heard, how_heard_other,
          terms_accepted_at, marketing_consent, last_login_at,
          created_at, updated_at`

func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByEmail,
		arg.Email, arg.FullName, arg.AvatarUrl, arg.IsEmailVerified)
	var u User
	err := row.Scan(
		&u.ID, &u.Email, &u.FullName, &u.AvatarUrl, &u.Phone,
		&u.IsEmailVerified, &u.IsPhoneVerified, &u.IsActive,
		&u.ProfileCompleted, &u.HowHeard, &u.HowHeardOther,
		&u.TermsAcceptedAt, &u.MarketingConsent, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

type CreateUserWithPasswordParams struct {
	Email            string
	FullName         sql.NullString
	PasswordHash     string
	TermsAccepted    bool
	MarketingConsent bool
}

const createUserWithPassword = `
INSERT INTO users (email, full_name, password_hash, terms_accepted_at, marketing_consent)
VALUES ($1, $2, $3, CASE WHEN $4 THEN now() ELSE NULL END, $5)
RETURNING id, email, full_name, avatar_url, phone,
          is_email_verified, is_phone_verified, is_active,
          profile_completed, how_heard, how_heard_other,
          terms_accepted_at, marketing_consent, last_login_at,
          created_at, updated_at`

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPassword, arg.Email, arg.FullName, arg.PasswordHash, arg.TermsAccepted, arg.MarketingConsent)
	var u User
	err := row.Scan(
		&u.ID, &u.Email, &u.FullName, &u.AvatarUrl, &u.Phone,
		&u.IsEmailVerified, &u.IsPhoneVerified, &u.IsActive,
		&u.ProfileCompleted, &u.HowHeard, &u.HowHeardOther,
		&u.TermsAcceptedAt, &u.MarketingConsent, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const getUserForLogin = `
SELECT id, email, full_name, avatar_url, phone,
       is_email_verified, is_phone_verified, is_active,
       profile_completed, how_heard, how_heard_other,
       terms_accepted_at, marketing_consent, last_login_at,
       created_at, updated_at, password_hash
FROM users WHERE email = $1`

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (UserForLogin, error) {
	row := q.db.QueryRowContext(ctx, getUserForLogin, email)
	var u UserForLogin
	err := row.Scan(
		&u.ID, &u.Email, &u.FullName, &u.AvatarUrl, &u.Phone,
		&u.IsEmailVerified, &u.IsPhoneVerified, &u.IsActive,
		&u.ProfileCompleted, &u.HowHeard, &u.HowHeardOther,
		&u.TermsAcceptedAt, &u.MarketingConsent, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt, &u.PasswordHash,
	)
	return u, err
}

const updateLastLogin = `UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}

// ── auth_identities ───────────────────────────────────────────────────────────

const getIdentityByProviderUID = `
SELECT id, user_id, provider, provider_uid, provider_email,
       provider_name, provider_avatar, access_token, refresh_token,
       token_expires_at, apple_name_captured, is_primary,
       last_used_at, created_at, updated_at
FROM auth_identities WHERE provider = $1 AND provider_uid = $2`

func (q *Queries) GetIdentityByProviderUID(ctx context.Context, provider, providerUID string) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProviderUID, provider, providerUID)
	return scanIdentity(row)
}

const getIdentityByUserAndProvider = `
SELECT id, user_id, provider, provider_uid, provider_email,
       provider_name, provider_avatar, access_token, refresh_token,
       token_expires_at, apple_name_captured, is_primary,
       last_used_at, created_at, updated_at
FROM auth_identities WHERE user_id = $1 AND provider = $2`

func (q *Queries) GetIdentityByUserAndProvider(ctx context.Context, userID uuid.UUID, provider string) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByUserAndProvider, userID, provider)
	return scanIdentity(row)
}

const upsertEmailIdentity = `
INSERT INTO auth_identities (user_id, provider, provider_uid, is_primary)
VALUES ($1, 'email', $2, true)
ON CONFLICT (user_id, provider) DO UPDATE
SET last_used_at = now(), updated_at = now()
RETURNING id, user_id, provider, provider_uid, provider_email,
          provider_name, provider_avatar, access_token, refresh_token,
          token_expires_at, apple_name_captured, is_primary,
          last_used_at, created_at, updated_at`

func (q *Queries) UpsertEmailIdentity(ctx context.Context, userID uuid.UUID, providerUID string) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, upsertEmailIdentity, userID, providerUID)
	return scanIdentity(row)
}

type CreateOAuthIdentityParams struct {
	UserID             uuid.UUID
	Provider           string
	ProviderUID        string
	ProviderEmail      sql.NullString
	ProviderName       sql.NullString
	ProviderAvatar     sql.NullString
	AccessToken        sql.NullString
	RefreshToken       sql.NullString
	TokenExpiresAt     sql.NullTime
	AppleNameCaptured  bool
	IsPrimary          bool
}

const createOAuthIdentity = `
INSERT INTO auth_identities (
    user_id, provider, provider_uid, provider_email, provider_name,
    provider_avatar, access_token, refresh_token, token_expires_at,
    apple_name_captured, is_primary
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, provider, provider_uid, provider_email,
          provider_name, provider_avatar, access_token, refresh_token,
          token_expires_at, apple_name_captured, is_primary,
          last_used_at, created_at, updated_at`

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, createOAuthIdentity,
		arg.UserID, arg.Provider, arg.ProviderUID, arg.ProviderEmail,
		arg.ProviderName, arg.ProviderAvatar, arg.AccessToken, arg.RefreshToken,
		arg.TokenExpiresAt, arg.AppleNameCaptured, arg.IsPrimary,
	)
	return scanIdentity(row)
}

type UpdateOAuthTokensParams struct {
	ID           uuid.UUID
	AccessToken  sql.NullString
	RefreshToken sql.NullString
	TokenExpires sql.NullTime
}

const updateOAuthTokens = `
UPDATE auth_identities
SET access_token = $2, refresh_token = $3, token_expires_at = $4,
    last_used_at = now(), updated_at = now()
WHERE id = $1`

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthTokens,
		arg.ID, arg.AccessToken, arg.RefreshToken, arg.TokenExpires)
	return err
}

const updateIdentityLastUsed = `UPDATE auth_identities SET last_used_at = now(), updated_at = now() WHERE id = $1`

func (q *Queries) UpdateIdentityLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateIdentityLastUsed, id)
	return err
}

func scanIdentity(row *sql.Row) (AuthIdentity, error) {
	var i AuthIdentity
	err := row.Scan(
		&i.ID, &i.UserID, &i.Provider, &i.ProviderUid,
		&i.ProviderEmail, &i.ProviderName, &i.ProviderAvatar,
		&i.AccessToken, &i.RefreshToken, &i.TokenExpiresAt,
		&i.AppleNameCaptured, &i.IsPrimary, &i.LastUsedAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

// ── otp_sessions ──────────────────────────────────────────────────────────────

type CreateOTPSessionParams struct {
	Email        string
	SessionToken string
	OtpHash      string
	ExpiresAt    time.Time
}

const createOTPSession = `
INSERT INTO otp_sessions (email, session_token, otp_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, session_token, otp_hash, attempts, expires_at, used_at, created_at`

func (q *Queries) CreateOTPSession(ctx context.Context, arg CreateOTPSessionParams) (OtpSession, error) {
	row := q.db.QueryRowContext(ctx, createOTPSession, arg.Email, arg.SessionToken, arg.OtpHash, arg.ExpiresAt)
	return scanOTPSession(row)
}

const getOTPSessionByToken = `
SELECT id, email, session_token, otp_hash, attempts, expires_at, used_at, created_at
FROM otp_sessions WHERE session_token = $1`

func (q *Queries) GetOTPSessionByToken(ctx context.Context, token string) (OtpSession, error) {
	row := q.db.QueryRowContext(ctx, getOTPSessionByToken, token)
	return scanOTPSession(row)
}

const incrementOTPAttempts = `
UPDATE otp_sessions SET attempts = attempts + 1 WHERE id = $1
RETURNING id, email, session_token, otp_hash, attempts, expires_at, used_at, created_at`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpSession, error) {
	row := q.db.QueryRowContext(ctx, incrementOTPAttempts, id)
	return scanOTPSession(row)
}

const markOTPSessionUsed = `UPDATE otp_sessions SET used_at = now() WHERE id = $1`

func (q *Queries) MarkOTPSessionUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOTPSessionUsed, id)
	return err
}

func scanOTPSession(row *sql.Row) (OtpSession, error) {
	var s OtpSession
	err := row.Scan(&s.ID, &s.Email, &s.SessionToken, &s.OtpHash, &s.Attempts, &s.ExpiresAt, &s.UsedAt, &s.CreatedAt)
	return s, err
}

// ── refresh_tokens ────────────────────────────────────────────────────────────

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	DeviceID  sql.NullString
	UserAgent sql.NullString
	IpAddress sql.NullString
	ExpiresAt time.Time
}

const createRefreshToken = `
INSERT INTO refresh_tokens (
    user_id, token_hash, family_id, device_id, user_agent, ip_address, expires_at
) VALUES ($1, $2, $3, $4, $5, $6::inet, $7)
RETURNING id, user_id, token_hash, family_id, device_id, user_agent,
          ip_address::text, expires_at, revoked_at, created_at`

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.UserID, arg.TokenHash, arg.FamilyID,
		arg.DeviceID, arg.UserAgent, arg.IpAddress, arg.ExpiresAt,
	)
	return scanRefreshToken(row)
}

const getRefreshTokenByHash = `
SELECT id, user_id, token_hash, family_id, device_id, user_agent,
       ip_address::text, expires_at, revoked_at, created_at
FROM refresh_tokens WHERE token_hash = $1`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, hash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, hash)
	return scanRefreshToken(row)
}

const getTokensByFamily = `
SELECT id, user_id, token_hash, family_id, device_id, user_agent,
       ip_address::text, expires_at, revoked_at, created_at
FROM refresh_tokens WHERE family_id = $1`

func (q *Queries) GetTokensByFamily(ctx context.Context, familyID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.QueryContext(ctx, getTokensByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tokens []RefreshToken
	for rows.Next() {
		var t RefreshToken
		if err = rows.Scan(
			&t.ID, &t.UserID, &t.TokenHash, &t.FamilyID,
			&t.DeviceID, &t.UserAgent, &t.IpAddress,
			&t.ExpiresAt, &t.RevokedAt, &t.CreatedAt,
		); err != nil {
			return nil, err
		}
		tokens = append(tokens, t)
	}
	return tokens, rows.Err()
}

const revokeRefreshToken = `UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}

const revokeTokenFamily = `UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL`

func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeTokenFamily, familyID)
	return err
}

func scanRefreshToken(row *sql.Row) (RefreshToken, error) {
	var t RefreshToken
	err := row.Scan(
		&t.ID, &t.UserID, &t.TokenHash, &t.FamilyID,
		&t.DeviceID, &t.UserAgent, &t.IpAddress,
		&t.ExpiresAt, &t.RevokedAt, &t.CreatedAt,
	)
	return t, err
}

// ── buyer_profiles ────────────────────────────────────────────────────────────

const createBuyerProfile = `
INSERT INTO buyer_profiles (user_id) VALUES ($1)
RETURNING id, user_id, total_orders, total_spent, created_at, updated_at`

func (q *Queries) CreateBuyerProfile(ctx context.Context, userID uuid.UUID) (BuyerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, createBuyerProfile, userID)
	return scanBuyerProfile(row)
}

const ensureBuyerProfile = `INSERT INTO buyer_profiles (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING`

func (q *Queries) EnsureBuyerProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ensureBuyerProfile, userID)
	return err
}

const getBuyerProfileByUserID = `
SELECT id, user_id, total_orders, total_spent, created_at, updated_at
FROM buyer_profiles WHERE user_id = $1`

func (q *Queries) GetBuyerProfileByUserID(ctx context.Context, userID uuid.UUID) (BuyerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getBuyerProfileByUserID, userID)
	return scanBuyerProfile(row)
}

func scanBuyerProfile(row *sql.Row) (BuyerProfileRow, error) {
	var p BuyerProfileRow
	err := row.Scan(&p.ID, &p.UserID, &p.TotalOrders, &p.TotalSpent, &p.CreatedAt, &p.UpdatedAt)
	return p, err
}
